config/routes.rb
Rails.application.routes.draw do
  resources :locations
  resources :resturants do 
    member do
      post "create_review"
    end
    collection do
      get "manage_resturants"
    end
  end
  post '/rate' => 'rater#create', :as => 'rate'
  resources :hotels do
    collection do
      get "manage_hotels"
    end
  end
  resources :attractions do
    collection do
      get "manage_attractions"
    end
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "hotels#index"
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>", large: "200x200" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  belongs_to :user
   ratyrate_rateable "name"
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit,:new, :update, :destroy]
  # GET /hotels
  # GET /hotels.json
  def index
    @hotels = Hotel.all
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  def manage_hotels
    @hotels = current_user.hotels
  end
  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = current_user.hotels.create(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: 'Hotel was successfully created.' }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1
  # PATCH/PUT /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to @hotel, notice: 'Hotel was successfully updated.' }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel.destroy
    respond_to do |format|
      format.html { redirect_to hotels_url, notice: 'Hotel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hotel_params
      params.require(:hotel).permit(:name, :description, :avatar,:location_id)
    end
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/_form.html.erb
<%= form_with(model: hotel, local: true) do |form| %>
<% if hotel.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

  <ul>
    <% hotel.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= form.label :name %>
  <%= form.text_field :name, id: :hotel_name %>
</div>

<div class="field">
  <%= form.label :description %>
  <%= form.text_area :description, id: :city_name %>
</div>
 <div class = "field">
    <%= form.file_field :avatar, as: :file  %>
  </div>
<div class="field">
  <%= form.label :location_id %>
  <%= form.number_field :location_id, id: :location_id %>
</div>
<div class="actions">
  <%= form.submit %>
</div>

<% end %>

app/views/hotels/edit.html.erb
<h1>Editing Hotel</h1>

<%= render 'form', hotel: @hotel %>

<%= link_to 'Show', @hotel %> |
<%= link_to 'Back', hotels_path %>

app/views/hotels/index.html.erb
<div class = "container">
  <div class = "row">
  <% @hotels.each_with_index do |hotel, index| %>
    <div class = "col-lg-4 col-md-4  col-sm-4">
      <%= image_tag hotel.avatar.url(:medium) %>
      <br>
      <%= link_to hotel.name, hotel_path(hotel) %>
    </div>
  <% end %>
</div>
</div>

app/views/hotels/manage_hotels.html.erb
<div class="container">
  <h2>My attractions</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Edit</th>
        <th>Destroy</th>
      </tr>
    </thead>
    <tbody>
      <% @hotels.each do |attr| %>
      <tr>
        <td><%= attr.name %></td>
        <td><%= link_to "Edit", edit_hotel_path(attr) %></td>
        <td><%= link_to "Delete", hotel_path(attr), :confirm => "Are you sure?", :method => :delete %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/hotels/new.html.erb
<h1>New Hotel</h1>

<%= render 'form', hotel: @hotel %>

<%= link_to 'Back', hotels_path %>

app/views/hotels/show.html.erb
<div class = "container" >
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @hotel.name %>
  </p>
  <%= image_tag @hotel.avatar.url(:medium) %>
  <br> 
  <p>
    <strong>Description:</strong>
    <%= @hotel.description %>
  </p>
  <% if current_user %>
    <% if current_user.user_type != 1 %>
      <p>
        <Strong> Average Ratings: </Strong> <%= rating_for @hotel, 'name' %>
      </p>
    <% end %>
    
  <% end %>
</div>