config/routes.rb
Rails.application.routes.draw do
  resources :locations
  resources :resturants do 
    member do
      post "create_review"
    end
    collection do
      get "manage_resturants"
    end
  end
  post '/rate' => 'rater#create', :as => 'rate'
  resources :hotels do
    collection do
      get "manage_hotels"
    end
  end
  resources :attractions do
    collection do
      get "manage_attractions"
    end
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "hotels#index"
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="#">Trip Advisor</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <% if current_user && current_user.user_type == 1 %>
         <li class="nav-item active">
          <%= link_to "Create Attraction", new_attraction_path , class: "nav-link" %>
        </li>
         <li class="nav-item active">
          <%= link_to "Create Hotel",new_hotel_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Add Location",new_location_path, class: "nav-link" %>
        </li>
         <li class="nav-item active">
          <%= link_to "Create Resturant",new_resturant_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Manage Attractions",manage_attractions_attractions_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Manage Hotels",manage_hotels_hotels_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Manage Resturants", manage_resturants_resturants_path, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to "Hotels", hotels_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Resturants", resturants_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Locations", locations_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Attractions", attractions_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <span class="navbar-text">
      <% if current_user %>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Sign In", new_user_session_path %>
        <%= link_to "Sign Up", new_user_registration_path  %>
      <% end %>
    </span>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebProjectFalah</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
     <%= render "layouts/nav" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container center">
    <div class="row">
      <div class="col-lg-12 col-xs-12 col-sm-12 col-md-12 text-center">
        <%= yield %>
      </div>
    </div>
  </div>
  </body>
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
</html>