config/routes.rb
Rails.application.routes.draw do
  resources :locations
  resources :resturants do 
    member do
      post "create_review"
    end
    collection do
      get "manage_resturants"
    end
  end
  post '/rate' => 'rater#create', :as => 'rate'
  resources :hotels do
    collection do
      get "manage_hotels"
    end
  end
  resources :attractions do
    collection do
      get "manage_attractions"
    end
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "hotels#index"
end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  before_action :set_attraction, only: [:show, :edit, :update, :destroy]

  # GET /attractions
  # GET /attractions.json
  def index
    @attractions = Attraction.all
  end

  # GET /attractions/1
  # GET /attractions/1.json
  def show
  end

  # GET /attractions/new
  def new
    @attraction = Attraction.new
  end

  # GET /attractions/1/edit
  def edit
  end

  def manage_attractions
    @attractions = current_user.attractions
  end

  # POST /attractions
  # POST /attractions.json
  def create
    @attraction = current_user.attractions.new(attraction_params)

    respond_to do |format|
      if @attraction.save
        format.html { redirect_to @attraction, notice: 'Attraction was successfully created.' }
        format.json { render :show, status: :created, location: @attraction }
      else
        format.html { render :new }
        format.json { render json: @attraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attractions/1
  # PATCH/PUT /attractions/1.json
  def update
    respond_to do |format|
      if @attraction.update(attraction_params)
        format.html { redirect_to @attraction, notice: 'Attraction was successfully updated.' }
        format.json { render :show, status: :ok, location: @attraction }
      else
        format.html { render :edit }
        format.json { render json: @attraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attractions/1
  # DELETE /attractions/1.json
  def destroy
    @attraction.destroy
    respond_to do |format|
      format.html { redirect_to attractions_url, notice: 'Attraction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attraction
      @attraction = Attraction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attraction_params
      params.require(:attraction).permit(:name, :description, :avatar,:location_id)
    end
end

app/helpers/attractions_helper.rb
module AttractionsHelper
end

app/views/attractions/_form.html.erb
<%= form_with(model: attraction, local: true) do |form| %>
<% if attraction.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(attraction.errors.count, "error") %> prohibited this attraction from being saved:</h2>

  <ul>
    <% attraction.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= form.label :name %>
  <%= form.text_field :name, id: :attraction_name %>
</div>

<div class="field">
  <%= form.label :description %>
  <%= form.text_field :description, id: :attraction_description %>
</div>

<div class = "field">
  <%= form.file_field :avatar  %>
</div>

<div class="field">
  <%= form.label :location_id %>
  <%= form.number_field :location_id, id: :location_id %>
</div>
<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/attractions/edit.html.erb
<h1>Editing Attraction</h1>

<%= render 'form', attraction: @attraction %>

<%= link_to 'Show', @attraction %> |
<%= link_to 'Back', attractions_path %>

app/views/attractions/index.html.erb
<div class = "container" >
  <h2> Attractions </h2>
  <% if @attractions.present? %>
    <div class = "container">
      <div class = "row">
      <% @attractions.each_with_index do |attraction, index| %>
        <div class = "col-lg-4 col-md-4  col-sm-4">
          <%= image_tag attraction.avatar.url(:medium) %>
          <br>
          <%= link_to attraction.name, attraction_path(attraction) %>
        </div>
      <% end %>
    </div>
    </div>
  <% end %>
</div>

app/views/attractions/manage_attractions.html.erb
<div class="container">
  <h2>My attractions</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Edit</th>
        <th>Destroy</th>
      </tr>
    </thead>
    <tbody>
      <% @attractions.each do |attr| %>
      <tr>
        <td><%= attr.name %></td>
        <td><%= link_to "Edit", edit_attraction_path(attr) %></td>
        <td><%= link_to "Delete", attraction_path(attr), :confirm => "Are you sure?", :method => :delete %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/attractions/new.html.erb
<h1>New Attraction</h1>

<%= render 'form', attraction: @attraction %>

<%= link_to 'Back', attractions_path %>

app/views/attractions/show.html.erb
<div class = "container" >
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @attraction.name %>
  </p>
  <%= image_tag @attraction.avatar.url(:medium) %>
  <br> 
  <p>
    <strong>Description:</strong>
    <%= @attraction.description %>
  </p>
</div>